#!/bin/bash

# /etc/init.d/sample.py
### BEGIN INIT INFO
# Provides:          shutdown with c button
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: wait for button c to shutdown
# Description:       wait for button c to shutdown
### END INIT INFO


function start() {
	/home/pi/rpi-scrollphathd/btn-shutdown.py > /home/pi/btn-shutdown.log 2>&1 &
	echo $! > /home/pi/btn-shutdown.pid
}

function stop() {
	pid=$(cat /home/pi/btn-shutdown.pid)
	kill $pid
	sleep 10
	if [ -e /proc/$pid ]; then
		kill -9 $pid
		sleep 5
	fi
}

cmd=$1
shift
case $cmd in
	start) start $@ ;;
	stop) stop $@ ;;
	restart) stop $@ && start $@ ;;
esac
