#!/bin/bash

# /etc/init.d/sample.py
### BEGIN INIT INFO
# Provides:          clock-init
# Required-Start:    $remote_fs $syslog $network $time
# Required-Stop:     $remote_fs $syslog $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start lcd clock display at boot time
# Description:       Start lcd clock display at boot time
### END INIT INFO


function start() {
	/home/pi/Pimoroni/scrollphathd/examples/matt.py > /home/pi/matt.log 2>&1 &
	echo $! > /home/pi/matt.pid
}

function stop() {
	pid=$(cat /home/pi/matt.pid)
	kill $pid
	sleep 10
	if [ -e /proc/$pid ]; then
		kill -9 $pid
		sleep 5
	fi
	/home/pi/Pimoroni/scrollphathd/examples/matt-stop.py
}

cmd=$1
shift
case $cmd in
	start) start $@ ;;
	stop) stop $@ ;;
	restart) stop $@ && start $@ ;;
esac
